# Generated by Django 5.1.1 on 2024-09-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='external_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
