# Generated by Django 5.1.1 on 2024-09-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="/media/default.jpg", upload_to="product_image"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="/media/default.jpg", upload_to="avatars"),
            preserve_default=False,
        ),
    ]
